version: "3.0"

services:
  # database service
  db:
    image: mariadb:latest
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbg-sql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - dbg-net

  # wordpress
  wp:
    env_file:
      - .env
    environment:
      WP_SITEURL: ${WP_HOME}/wp
    build:
      dockerfile: docker/local.Dockerfile
      context: "."
    # mounting local volume for hot-reload
    volumes:
      - ./site:/data
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - dbg-net

networks:
  dbg-net:

volumes:
  dbg-sql-data:
